//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tıbbitakipsistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tahlil
    {
        public int ID { get; set; }
        public int KullaniciId { get; set; }
        public string Tarih { get; set; }
        public string TahlilBilgisi { get; set; }
        public Nullable<bool> TahlilSonuc { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
